---
abstract: 'add pleasant whitespace to a DOM tree'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  Test::More: '0.96'
  Test::Warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.016, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-LibXML-PrettyPrint
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  XML::LibXML::PrettyPrint:
    file: lib/XML/LibXML/PrettyPrint.pm
    version: '0.006'
requires:
  Exporter::Tiny: '0'
  XML::LibXML: '1.62'
  perl: '5.008001'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/XML-LibXML-PrettyPrint/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-LibXML-PrettyPrint
  homepage: https://metacpan.org/release/XML-LibXML-PrettyPrint
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-xml-libxml-prettyprint.git
version: '0.006'
x_provides_scripts:
  xml-pretty:
    file: bin/xml-pretty
